version: '3.8'

services:
  app:
    build: .
    container_name: nest-api
    restart: always
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
